version: '3.8'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql_db
    restart: always
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "YourStrong!Passw0rd"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    networks:
      - mssql_network

  adminer:
    image: adminer
    container_name: mssql_adminer
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: "mssql"
    depends_on:
      - mssql
    networks:
      - mssql_network

volumes:
  mssql_data:
    driver: local
    driver_opts:
      type: none
      device: /var/mssql
      o: bind

networks:
  mssql_network:
    driver: bridge
